// Polyfill Module Index - Re-exports all polyfill functionality

// Sync methods
export {
    setRequestFn,
    readFileSync,
    writeFileSync,
    appendFileSync,
    existsSync,
    accessSync,
    unlinkSync,
    rmSync,
    mkdirSync,
    rmdirSync,
    readdirSync,
    opendirSync,
    statSync,
    lstatSync,
    statfsSync,
    renameSync,
    copyFileSync,
    cpSync,
    truncateSync,
    chmodSync,
    chownSync,
    lchmodSync,
    lchownSync,
    linkSync,
    symlinkSync,
    readlinkSync,
    realpathSync,
    mkdtempSync,
    utimesSync,
    lutimesSync,
    openSync,
    closeSync,
    readSync,
    writeSync,
    fstatSync,
    fsyncSync,
    fdatasyncSync,
    ftruncateSync,
    fchmodSync,
    fchownSync,
    futimesSync,
    readvSync,
    writevSync,
    globSync,
} from './sync'

// Async methods
export {
    setAsyncRequestFn,
    setFireAndForgetFn,
    setSyncRequestFn,
    readFile,
    writeFile,
    appendFile,
    exists,
    access,
    unlink,
    rm,
    mkdir,
    rmdir,
    readdir,
    opendir,
    stat,
    lstat,
    statfs,
    rename,
    copyFile,
    cp,
    truncate,
    chmod,
    chown,
    lchmod,
    lchown,
    link,
    symlink,
    readlink,
    realpath,
    mkdtemp,
    utimes,
    lutimes,
    open,
    close,
    read,
    write,
    fstat,
    fsync,
    fdatasync,
    ftruncate,
    fchmod,
    fchown,
    futimes,
    readv,
    writev,
    watch,
    glob,
    watchFile,
    unwatchFile,
    createReadStream,
    createWriteStream,
    vfsLoad,
    vfsExtract,
} from './async'

// Types
export type { FSWatcher } from './async'
